[commands.build]
script = [
  "cmake -G%{generator} -DCMAKE_BUILD_TYPE=%{target} -B build/%{target}",
  "ninja -C build/%{target}"
]
description = "Build the application for a given target."

[commands.dist]
script = [
  "litr build --target=release",
  "cpack --config build/release/CPackConfig.cmake"
]
description = "Create the application distribution package from a release build."

[commands.start]
script = "cd ./build/%{target}/src/app && ./App"
description = "Start the application."

[commands.test]
script = "echo 'No tests defined, yet!'"
description = "Run all tests."

[commands.format]
script = "find src -iname *.hpp -o -iname *.cpp | xargs clang-format -i"
description = "Format project sources via clang-format."

[params.target]
shortcut = "t"
description = "Define the application build target."
type = ["debug", "release"]
default = "debug"

[params.generator]
shortcut = "g"
description = "Define the CMake generator."
type = ["Ninja", "Xcode"]
default = "Ninja"
